/**
 * Heal engine — routes lint findings to appropriate repair functions.
 *
 * Per D-11 through D-14:
 * - missing-concept: create stub articles via LLM
 * - missing-cross-ref: add See Also entries via upsertSeeAlsoEntry
 * - orphan: add backlinks from BM25 top match via upsertSeeAlsoEntry
 * - stale: log recommendation (full re-fetch is the ask pipeline)
 * - contradiction: NEVER auto-fix, output to stderr for human review
 *
 * Per D-17 (T-09-06): --dry-run gates ALL mutations (saveArticle + rippleUpdates + enforceBacklinks).
 * Per RESEARCH Pitfall 2: Sequential processing for large wiki safety.
 */

import type { Article, Frontmatter } from '../types/article.js';
import type { WikiStore } from '../store/wiki-store.js';
import type { Config } from '../config/config.js';
import type { LintFinding } from './linter.js';
import { generateText } from '../llm/adapter.js';
import { parseArticleOutput } from '../synthesis/output-parser.js';
import { upsertSeeAlsoEntry } from '../synthesis/see-also.js';
import { buildIndex, search } from '../search/search-index.js';
import { rippleUpdates } from '../synthesis/ripple.js';
import { enforceBacklinks } from '../synthesis/backlink-enforcer.js';
import slugifyLib from 'slugify';

// ---- Types ----

export interface HealResult {
  fixed: number;
  skipped: number;
  errors: number;
  humanReview: string[];  // contradiction descriptions
}

// ---- Helpers ----

/**
 * Convert a slug to a display title.
 * "machine-learning" → "Machine Learning"
 */
function slugToTitle(slug: string): string {
  return slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

/**
 * Build stub article prompt for missing-concept healing.
 */
function buildStubPrompt(title: string, referencedIn: string[], schema: string): string {
  const referenceList =
    referencedIn.length > 0
      ? `This concept is referenced in: ${referencedIn.join(', ')}`
      : 'This concept was found referenced in the wiki.';

  return `You are creating a stub wiki article for a concept that is referenced but not yet documented.

Wiki schema for context:
${schema}

${referenceList}

Create a minimal wiki article for the concept: "${title}"

Requirements:
- Keep it concise — this is a stub to be expanded later
- Include a brief definition and key points
- Add a note: "This article was auto-generated by wiki heal. Expand it by running: wiki ask \\"${title}\\""
- Include relevant tags and categories

Respond in this exact format:
TITLE: ${title}
SUMMARY: <one sentence summary>
CATEGORIES: <comma-separated categories>
BODY:
<markdown body with 1-2 paragraphs and the auto-generated note>`;
}

// ---- Routing functions ----

/**
 * D-12: Heal missing-concept by creating a stub article via LLM.
 */
async function healMissingConcept(
  finding: LintFinding,
  store: WikiStore,
  config: Config,
  schema: string,
  dryRun: boolean
): Promise<void> {
  const conceptSlug = finding.affected[0];
  if (!conceptSlug) {
    throw new Error('missing-concept finding has no affected slug');
  }

  const title = slugToTitle(conceptSlug);

  if (dryRun) {
    process.stderr.write(`[heal] [DRY-RUN] Would create stub: "${title}"\n`);
    return;
  }

  const prompt = buildStubPrompt(title, finding.affected.slice(1), schema);

  let raw = await generateText(prompt, { temperature: 0.3, maxOutputTokens: 1024 });
  let parsed = parseArticleOutput(raw);

  // Retry once with stronger format instruction (same retry pattern as file.ts)
  if (!parsed) {
    const retryPrompt = `${prompt}\n\nIMPORTANT: You MUST start your response with "TITLE:" on the very first line. Do not include any preamble or explanation.`;
    raw = await generateText(retryPrompt, { temperature: 0.2, maxOutputTokens: 1024 });
    parsed = parseArticleOutput(raw);
  }

  if (!parsed) {
    throw new Error(`Failed to parse LLM output for stub article: "${title}"`);
  }

  // Build Article with type 'filed', slug via slugifyLib, current timestamp
  const now = new Date().toISOString();
  const slug = slugifyLib(parsed.title, { lower: true, strict: true });

  const frontmatter: Frontmatter = {
    title: parsed.title,
    tags: [],
    categories: parsed.categories.length > 0 ? parsed.categories : ['Uncategorized'],
    sources: [],
    sourced_at: null,
    type: 'filed',
    created_at: now,
    updated_at: now,
    summary: parsed.summary || `Stub article for ${title}.`,
  };

  const article: Article = {
    slug,
    frontmatter,
    body: parsed.body,
  };

  await store.saveArticle(article, 'create');

  // Post-heal: ripple + backlink enforcement
  await rippleUpdates([article], store, schema);
  await enforceBacklinks(article, store);
}

/**
 * D-12: Heal missing-cross-ref by adding a See Also entry.
 * affected array: [articleSlug, matchSlug]
 */
async function healMissingCrossRef(
  finding: LintFinding,
  store: WikiStore,
  schema: string,
  dryRun: boolean
): Promise<void> {
  const [articleSlug, matchSlug] = finding.affected;
  if (!articleSlug || !matchSlug) {
    throw new Error('missing-cross-ref finding requires 2 affected slugs');
  }

  if (dryRun) {
    process.stderr.write(`[heal] [DRY-RUN] Would add cross-ref: [[${articleSlug}]] ↔ [[${matchSlug}]]\n`);
    return;
  }

  const article = await store.getArticle(articleSlug);
  if (!article) {
    process.stderr.write(`[heal] Warning: article "${articleSlug}" not found — skipping cross-ref fix\n`);
    return;
  }

  const entry = `[[${matchSlug}]] - Related concept`;
  const updatedBody = upsertSeeAlsoEntry(article.body, entry);

  if (updatedBody !== article.body) {
    await store.saveArticle({ ...article, body: updatedBody }, 'update');
    await enforceBacklinks({ ...article, body: updatedBody }, store);
  }
}

/**
 * D-12: Heal stale article — log recommended action.
 * The full re-fetch is a complex 10-step pipeline better done via `wiki ask --refresh`.
 */
function healStale(finding: LintFinding, dryRun: boolean): void {
  const slug = finding.affected[0] ?? 'unknown';
  const title = slugToTitle(slug);

  if (dryRun) {
    process.stderr.write(`[heal] [DRY-RUN] Would recommend re-fetch for stale article: "${slug}"\n`);
    return;
  }

  process.stderr.write(`[heal] Stale article "${slug}" — run: wiki ask "${title}" --refresh\n`);
}

/**
 * D-12: Heal orphan by adding a backlink from the BM25 top match.
 */
async function healOrphan(
  finding: LintFinding,
  store: WikiStore,
  schema: string,
  dryRun: boolean
): Promise<void> {
  const orphanSlug = finding.affected[0];
  if (!orphanSlug) {
    throw new Error('orphan finding has no affected slug');
  }

  const orphanTitle = slugToTitle(orphanSlug);

  if (dryRun) {
    process.stderr.write(`[heal] [DRY-RUN] Would add backlink to orphan: "${orphanSlug}"\n`);
    return;
  }

  // Load all articles, build BM25 index
  const allArticles = await store.listArticles();
  if (allArticles.length === 0) {
    process.stderr.write(`[heal] Warning: no articles to find a match for orphan "${orphanSlug}"\n`);
    return;
  }

  const index = buildIndex(allArticles);
  const results = search(index, orphanTitle);

  // Get top match excluding the orphan itself
  const topMatch = results.find((r) => r.slug !== orphanSlug);
  if (!topMatch) {
    process.stderr.write(`[heal] Warning: no related article found for orphan "${orphanSlug}"\n`);
    return;
  }

  const topMatchArticle = await store.getArticle(topMatch.slug);
  if (!topMatchArticle) {
    process.stderr.write(`[heal] Warning: top match article "${topMatch.slug}" not found\n`);
    return;
  }

  const entry = `[[${orphanSlug}]] - Related: ${orphanTitle}`;
  const updatedBody = upsertSeeAlsoEntry(topMatchArticle.body, entry);

  if (updatedBody !== topMatchArticle.body) {
    await store.saveArticle({ ...topMatchArticle, body: updatedBody }, 'update');
    await enforceBacklinks({ ...topMatchArticle, body: updatedBody }, store);
  }
}

/**
 * D-12: Contradiction — NEVER auto-fix.
 * Output to stderr for human review, add to humanReview array.
 */
function handleContradiction(finding: LintFinding, humanReview: string[]): void {
  const description = finding.suggestedFix;
  process.stderr.write(`[heal] [HUMAN REVIEW] Contradiction: ${description}\n`);
  humanReview.push(description);
}

// ---- Main export ----

/**
 * Route lint findings to appropriate repair functions.
 *
 * Per D-17: dryRun=true skips ALL mutations: saveArticle + rippleUpdates + enforceBacklinks.
 * Per RESEARCH Pitfall 2: Sequential processing (not Promise.all) for index safety.
 *
 * @param findings - Lint findings to process
 * @param store    - WikiStore instance (injected for testability)
 * @param config   - Wiki config
 * @param schema   - Wiki schema string (passed to LLM and ripple)
 * @param dryRun   - If true, log what would happen without making changes
 * @returns HealResult with counts of fixed, skipped, errors, and human-review items
 */
export async function healFindings(
  findings: LintFinding[],
  store: WikiStore,
  config: Config,
  schema: string,
  dryRun: boolean = false
): Promise<HealResult> {
  let fixed = 0;
  let skipped = 0;
  let errors = 0;
  const humanReview: string[] = [];

  // Sequential for loop — not Promise.all — to avoid index rebuild races (RESEARCH Pitfall 2)
  for (const finding of findings) {
    try {
      switch (finding.category) {
        case 'missing-concept':
          await healMissingConcept(finding, store, config, schema, dryRun);
          if (!dryRun) fixed++;
          else skipped++;
          break;

        case 'missing-cross-ref':
          await healMissingCrossRef(finding, store, schema, dryRun);
          if (!dryRun) fixed++;
          else skipped++;
          break;

        case 'stale':
          healStale(finding, dryRun);
          // Stale always counts as skipped — full re-fetch requires ask pipeline
          skipped++;
          break;

        case 'orphan':
          await healOrphan(finding, store, schema, dryRun);
          if (!dryRun) fixed++;
          else skipped++;
          break;

        case 'contradiction':
          handleContradiction(finding, humanReview);
          skipped++;
          break;

        default: {
          // Unknown category — log and skip
          const cat = (finding as LintFinding).category;
          process.stderr.write(`[heal] Unknown category "${cat}" — skipping\n`);
          skipped++;
        }
      }
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      process.stderr.write(`[heal] Error processing ${finding.category} (${finding.affected.join(', ')}): ${message}\n`);
      errors++;
    }
  }

  return { fixed, skipped, errors, humanReview };
}
