import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { Article } from '../src/types/article.js';
import type { LintFinding } from '../src/lint/linter.js';

// Mock LLM adapter
vi.mock('../src/llm/adapter.js', () => ({
  generateText: vi.fn(),
}));

// Mock search-index for BM25 control
vi.mock('../src/search/search-index.js', () => ({
  buildIndex: vi.fn().mockReturnValue({}),
  search: vi.fn().mockReturnValue([]),
}));

// Mock ripple and backlink-enforcer
vi.mock('../src/synthesis/ripple.js', () => ({
  rippleUpdates: vi.fn().mockResolvedValue({ updatedSlugs: [], skippedSlugs: [] }),
}));

vi.mock('../src/synthesis/backlink-enforcer.js', () => ({
  enforceBacklinks: vi.fn().mockResolvedValue([]),
}));

import { generateText } from '../src/llm/adapter.js';
import { buildIndex, search } from '../src/search/search-index.js';
import { rippleUpdates } from '../src/synthesis/ripple.js';
import { enforceBacklinks } from '../src/synthesis/backlink-enforcer.js';
import { healFindings } from '../src/lint/healer.js';

// ---- MockWikiStore ----

class MockWikiStore {
  private articles = new Map<string, Article>();

  slugify(title: string): string {
    return title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  }

  async saveArticle(article: Article, _operation?: 'create' | 'update'): Promise<string> {
    this.articles.set(article.slug, article);
    return `/tmp/vault/articles/${article.slug}.md`;
  }

  async listArticles(): Promise<Article[]> {
    return Array.from(this.articles.values());
  }

  async getArticle(slug: string): Promise<Article | null> {
    return this.articles.get(slug) ?? null;
  }

  async readSchema(): Promise<string | null> {
    return null;
  }

  async updateSchema(_content: string): Promise<void> {}

  async appendLog(_op: string, _desc: string): Promise<void> {}

  seedArticle(article: Article): void {
    this.articles.set(article.slug, article);
  }
}

// ---- Fixture helpers ----

function makeArticle(slug: string, title: string, summary: string, body?: string): Article {
  return {
    slug,
    frontmatter: {
      title,
      tags: [],
      categories: ['Test'],
      sources: [],
      sourced_at: null,
      type: 'web',
      created_at: '2026-04-04T00:00:00.000Z',
      updated_at: '2026-04-04T00:00:00.000Z',
      summary,
    },
    body: body ?? `## Overview\n\n${summary}\n`,
  };
}

function makeFinding(
  category: LintFinding['category'],
  affected: string[],
  suggestedFix = 'Fix this issue'
): LintFinding {
  return {
    category,
    severity: 'info',
    affected,
    suggestedFix,
  };
}

// ---- Tests ----

describe('healFindings()', () => {
  let store: MockWikiStore;
  const mockConfig = {
    vault_path: '/tmp/vault',
    llm_provider: 'claude' as const,
    search_provider: 'exa' as const,
    coverage_threshold: 5.0,
    freshness_days: 30,
  };

  const mockGenerateText = generateText as ReturnType<typeof vi.fn>;
  const mockBuildIndex = buildIndex as ReturnType<typeof vi.fn>;
  const mockSearch = search as ReturnType<typeof vi.fn>;
  const mockRippleUpdates = rippleUpdates as ReturnType<typeof vi.fn>;
  const mockEnforceBacklinks = enforceBacklinks as ReturnType<typeof vi.fn>;

  beforeEach(() => {
    store = new MockWikiStore();
    mockGenerateText.mockReset();
    mockBuildIndex.mockReturnValue({});
    mockSearch.mockReturnValue([]);
    mockRippleUpdates.mockResolvedValue({ updatedSlugs: [], skippedSlugs: [] });
    mockEnforceBacklinks.mockResolvedValue([]);
    vi.spyOn(process.stderr, 'write').mockImplementation(() => true);
  });

  // Test 1: missing-concept creates stub article
  it('Test 1 (missing-concept): calls generateText with stub prompt and saveArticle with new article', async () => {
    const llmResponse = `TITLE: Machine Learning\nSUMMARY: A stub article for machine learning.\nCATEGORIES: Technology\nBODY:\n## Overview\n\nMachine learning is an auto-generated stub.\n\nThis article was auto-generated by wiki heal. Expand it by running: wiki ask "Machine Learning"`;
    mockGenerateText.mockResolvedValueOnce(llmResponse);

    const finding = makeFinding('missing-concept', ['machine-learning'], 'Create article for [[machine-learning]]');
    const saveArticleSpy = vi.spyOn(store, 'saveArticle');

    const result = await healFindings([finding], store, mockConfig, 'test-schema', false);

    expect(mockGenerateText).toHaveBeenCalledTimes(1);
    expect(saveArticleSpy).toHaveBeenCalledWith(
      expect.objectContaining({
        frontmatter: expect.objectContaining({ type: 'filed' }),
      }),
      'create'
    );
    expect(result.fixed).toBe(1);
    expect(result.errors).toBe(0);
  });

  // Test 2: slug to title conversion
  it('Test 2 (missing-concept title): slug machine-learning produces title "Machine Learning"', async () => {
    const llmResponse = `TITLE: Machine Learning\nSUMMARY: A stub article.\nCATEGORIES: Technology\nBODY:\n## Overview\n\nContent here. This article was auto-generated by wiki heal.`;
    mockGenerateText.mockResolvedValueOnce(llmResponse);

    const finding = makeFinding('missing-concept', ['machine-learning']);
    const saveArticleSpy = vi.spyOn(store, 'saveArticle');

    await healFindings([finding], store, mockConfig, 'test-schema', false);

    // Verify the article title passed to saveArticle is "Machine Learning" not "machine-learning"
    expect(saveArticleSpy).toHaveBeenCalledWith(
      expect.objectContaining({
        frontmatter: expect.objectContaining({ title: 'Machine Learning' }),
      }),
      'create'
    );
  });

  // Test 3: missing-cross-ref calls upsertSeeAlsoEntry and saveArticle
  it('Test 3 (missing-cross-ref): loads article, upserts See Also entry, saves updated body', async () => {
    const existingArticle = makeArticle('neural-networks', 'Neural Networks', 'Deep learning foundations');
    store.seedArticle(existingArticle);

    const finding = makeFinding('missing-cross-ref', ['neural-networks', 'machine-learning']);
    const saveArticleSpy = vi.spyOn(store, 'saveArticle');

    const result = await healFindings([finding], store, mockConfig, 'test-schema', false);

    expect(saveArticleSpy).toHaveBeenCalledWith(
      expect.objectContaining({
        slug: 'neural-networks',
        body: expect.stringContaining('[[machine-learning]]'),
      }),
      'update'
    );
    expect(result.fixed).toBe(1);
  });

  // Test 4: orphan finding — BM25 search finds top match, upserts backlink
  it('Test 4 (orphan): BM25 search finds top match, adds backlink from top match to orphan', async () => {
    const orphanArticle = makeArticle('orphan-article', 'Orphan Article', 'An article with no inbound links');
    const relatedArticle = makeArticle('related-article', 'Related Article', 'This article is related to the orphan');
    store.seedArticle(orphanArticle);
    store.seedArticle(relatedArticle);

    mockSearch.mockReturnValue([
      { slug: 'orphan-article', title: 'Orphan Article', summary: 'orphan', score: 8.0 },
      { slug: 'related-article', title: 'Related Article', summary: 'related', score: 6.0 },
    ]);

    const finding = makeFinding('orphan', ['orphan-article'], 'Add backlink from related article');
    const saveArticleSpy = vi.spyOn(store, 'saveArticle');

    const result = await healFindings([finding], store, mockConfig, 'test-schema', false);

    // Should save the related article (the top match excluding self) with a backlink to the orphan
    expect(saveArticleSpy).toHaveBeenCalledWith(
      expect.objectContaining({
        slug: 'related-article',
        body: expect.stringContaining('[[orphan-article]]'),
      }),
      'update'
    );
    expect(result.fixed).toBe(1);
  });

  // Test 5: contradiction — NO saveArticle, message to stderr
  it('Test 5 (contradiction): does NOT call saveArticle, writes to stderr, adds to humanReview', async () => {
    const finding = makeFinding('contradiction', ['article-a', 'article-b'], 'Review contradiction: Article A says X, Article B says Y');
    const saveArticleSpy = vi.spyOn(store, 'saveArticle');

    const result = await healFindings([finding], store, mockConfig, 'test-schema', false);

    expect(saveArticleSpy).not.toHaveBeenCalled();
    expect(process.stderr.write).toHaveBeenCalledWith(
      expect.stringContaining('HUMAN REVIEW')
    );
    expect(result.humanReview).toHaveLength(1);
    expect(result.skipped).toBe(1);
    expect(result.fixed).toBe(0);
  });

  // Test 6: stale — writes recommendation to stderr, increments skipped
  it('Test 6 (stale): writes recommendation to stderr, increments skipped count', async () => {
    const finding = makeFinding('stale', ['stale-article'], 'Re-fetch by running: wiki ask "Stale Article" --refresh');
    const saveArticleSpy = vi.spyOn(store, 'saveArticle');

    const result = await healFindings([finding], store, mockConfig, 'test-schema', false);

    expect(saveArticleSpy).not.toHaveBeenCalled();
    expect(process.stderr.write).toHaveBeenCalledWith(
      expect.stringContaining('stale-article')
    );
    expect(result.skipped).toBe(1);
    expect(result.fixed).toBe(0);
  });

  // Test 7: dry-run suppresses all mutations
  it('Test 7 (dry-run): dryRun=true suppresses saveArticle, rippleUpdates, and enforceBacklinks', async () => {
    const llmResponse = `TITLE: Machine Learning\nSUMMARY: A stub.\nCATEGORIES: Technology\nBODY:\n## Overview\n\nContent. This article was auto-generated by wiki heal.`;
    mockGenerateText.mockResolvedValueOnce(llmResponse);

    const findings: LintFinding[] = [
      makeFinding('missing-concept', ['machine-learning']),
    ];
    const saveArticleSpy = vi.spyOn(store, 'saveArticle');

    await healFindings(findings, store, mockConfig, 'test-schema', true);

    expect(saveArticleSpy).not.toHaveBeenCalled();
    expect(mockRippleUpdates).not.toHaveBeenCalled();
    expect(mockEnforceBacklinks).not.toHaveBeenCalled();
    // Should log DRY-RUN to stderr
    expect(process.stderr.write).toHaveBeenCalledWith(
      expect.stringContaining('DRY-RUN')
    );
  });

  // Test 8: sequential processing — verified by mock call order
  it('Test 8 (sequential): processes multiple findings in order (sequential not parallel)', async () => {
    const article1 = makeArticle('article-one', 'Article One', 'First article');
    const article2 = makeArticle('article-two', 'Article Two', 'Second article');
    store.seedArticle(article1);
    store.seedArticle(article2);

    const callOrder: string[] = [];
    const originalGetArticle = store.getArticle.bind(store);
    vi.spyOn(store, 'getArticle').mockImplementation(async (slug) => {
      callOrder.push(`getArticle:${slug}`);
      return originalGetArticle(slug);
    });

    const findings: LintFinding[] = [
      makeFinding('missing-cross-ref', ['article-one', 'article-two']),
      makeFinding('missing-cross-ref', ['article-two', 'article-one']),
    ];

    await healFindings(findings, store, mockConfig, 'test-schema', false);

    // Verify getArticle was called (implies sequential iteration)
    expect(callOrder.length).toBeGreaterThan(0);
    // First call should be for article-one (first finding)
    expect(callOrder[0]).toBe('getArticle:article-one');
  });

  // Test 9: per-item error — one finding fails, others still processed
  it('Test 9 (per-item error): one finding fails, subsequent findings still processed', async () => {
    const existingArticle = makeArticle('valid-article', 'Valid Article', 'This one exists');
    store.seedArticle(existingArticle);

    const llmResponse = `TITLE: New Concept\nSUMMARY: A stub.\nCATEGORIES: Technology\nBODY:\n## Overview\n\nContent. This article was auto-generated by wiki heal.`;

    // First generateText call throws, second succeeds (for the 2nd missing-concept finding)
    mockGenerateText
      .mockRejectedValueOnce(new Error('LLM API error'))
      .mockResolvedValueOnce(llmResponse);

    const findings: LintFinding[] = [
      makeFinding('missing-concept', ['failing-concept']),   // will throw
      makeFinding('missing-concept', ['new-concept']),       // should succeed
    ];
    const saveArticleSpy = vi.spyOn(store, 'saveArticle');

    const result = await healFindings(findings, store, mockConfig, 'test-schema', false);

    // First finding failed, second succeeded
    expect(result.errors).toBe(1);
    expect(result.fixed).toBe(1);
    // saveArticle called once for the successful finding
    expect(saveArticleSpy).toHaveBeenCalledTimes(
      expect.any(Number)  // at least once for the successful article
    );
  });

  // Test 10: ripple + backlink called after non-dry-run heal
  it('Test 10 (ripple+backlink): rippleUpdates and enforceBacklinks called for modified articles', async () => {
    const llmResponse = `TITLE: Machine Learning\nSUMMARY: A stub.\nCATEGORIES: Technology\nBODY:\n## Overview\n\nContent. This article was auto-generated by wiki heal.`;
    mockGenerateText.mockResolvedValueOnce(llmResponse);

    const finding = makeFinding('missing-concept', ['machine-learning']);

    await healFindings([finding], store, mockConfig, 'test-schema', false);

    // rippleUpdates and enforceBacklinks should be called after saving the article
    expect(mockRippleUpdates).toHaveBeenCalled();
    expect(mockEnforceBacklinks).toHaveBeenCalled();
  });
});
